using System.Collections.Generic;
using System.Windows;
using System.Windows.Forms;

namespace KMS_Eberhard_Michael
{

    public partial class MainWindow : Window
    {
        
        public List<Accounts> matches = new List<Accounts>();
        public MainWindow()
        {
            //InitializeComponent() is a method in a C# Windows Forms application that initializes all the components on a form.
            //It is typically called during the form's constructor, and sets the properties, events, and layout of the form's controls.
            //It is automatically generated by the Windows Forms Designer when a form is created in the Visual Studio designer,
            //and can be edited manually if necessary.
            InitializeComponent();                  
            btnLoadDetailsMain.IsEnabled = false;
            
        }
        
        private void btnLoadDataMain_Click(object sender, RoutedEventArgs e)
        {
            //opens a FolderBroserDialog to select the Folder where the csv files are located
            FolderBrowserDialog fbd = new FolderBrowserDialog();
            //opens the dialog
            fbd.ShowDialog();
            //safes the chosen filePath
            string filePath = fbd.SelectedPath;
            
            if (filePath.EndsWith(@"\DatenGoldIsMoney"))
            {
                //Calls the Methods to fill the lists
                Customers.LoadCustomers(filePath);
                Accounts.LoadAccounts(filePath);
                Orders.LoadOrders(filePath);

                //activates or disables buttons
                btnLoadDetailsMain.IsEnabled = true;
                listViewMain.ItemsSource = Customers.customers;
                btnLoadDataMain.IsEnabled = false;
            }
            else
            {
                System.Windows.MessageBox.Show("Please choose the 'DatenGoldIsMoney' folder or quit the programm");
            }            

        }

        private void btnLoadDetailsMain_Click(object sender, RoutedEventArgs e)
        {           
            try
            {
                CustomerAccounts.matchesNew.Clear();                
                int index = listViewMain.SelectedIndex;

                foreach (var act in Accounts.accounts)
                {
                    if (act.CustomerID == Customers.customers[index].Id)
                    {
                        matches.Add(act);
                    }
                }
                CustomerAccounts customerAccounts = new CustomerAccounts(matches, this);
                customerAccounts.Show();
                this.Hide();
            }
            catch
            {
                System.Windows.MessageBox.Show("Please choose a customer");
            }            
            
        }

        private void btnQuit_Click(object sender, RoutedEventArgs e)
        {
            App.Current.Shutdown();
        }
    }
}
